In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import LabelEncoder

In [2]:
train=pd.read_csv("E:\\data science\\assiments\\17\\SalaryData_Train(1).csv")
test =pd.read_csv("E:\\data science\\assiments\\17\\SalaryData_Test(1).csv")

In [3]:
train.head()

age          workclass   education  educationno        maritalstatus  \
0   39          State-gov   Bachelors           13        Never-married   
1   50   Self-emp-not-inc   Bachelors           13   Married-civ-spouse   
2   38            Private     HS-grad            9             Divorced   
3   53            Private        11th            7   Married-civ-spouse   
4   28            Private   Bachelors           13   Married-civ-spouse   

           occupation    relationship    race      sex  capitalgain  \
0        Adm-clerical   Not-in-family   White     Male         2174   
1     Exec-managerial         Husband   White     Male            0   
2   Handlers-cleaners   Not-in-family   White     Male            0   
3   Handlers-cleaners         Husband   Black     Male            0   
4      Prof-specialty            Wife   Black   Female            0   

   capitalloss  hoursperweek          native  Salary  
0            0            40   United-States   <=50K  
1            0            13   United-States   <=50K  
2            0            40   United-States   <=50K  
3            0            40   United-States   <=50K  
4            0            40            Cuba   <=50K

In [4]:
lb=LabelEncoder()

In [5]:
lst = ["workclass","education","maritalstatus","occupation","relationship","race","sex","native"]

In [6]:
for i in lst:
     train[i]= lb.fit_transform(train[i])
        

In [7]:
for i in lst:
     test[i]= lb.fit_transform(test[i])

In [8]:
x_train = train.iloc[:,0:102]
y_train = train["Salary"]

In [9]:
x_test = test.iloc[:,0:102]
y_test = test["Salary"]

In [10]:
x_test=x_test.drop(['Salary'],axis=1)

In [11]:
x_train=x_train.drop(['Salary'],axis=1)

### SVM with kernel rbf¶

In [12]:
clf = SVC(kernel="rbf")
clf.fit(x_train , y_train)
y_pred = clf.predict(x_test)
acc = accuracy_score(y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred)

Accuracy = 79.64143426294821


array([[10997,   363],
       [ 2703,   997]], dtype=int64)

### SVM with kernel poly

In [13]:
clf = SVC(kernel="poly")
clf.fit(x_train , y_train)
y_pred = clf.predict(x_test)
acc = accuracy_score(y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred)

Accuracy = 77.95484727755644


array([[11356,     4],
       [ 3316,   384]], dtype=int64)

 ### SVM with kernel sigmoid

In [14]:
clf = SVC(kernel="sigmoid")
clf.fit(x_train , y_train)
y_pred = clf.predict(x_test)
acc = accuracy_score(y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred)

Accuracy = 75.67729083665338


array([[10553,   807],
       [ 2856,   844]], dtype=int64)

## SVM with kernel poly have best accuracy